name: Auto-approve Owner's Pull Requests

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Allows manual runs

jobs:
  auto-approve:
    uses: TheManOfTeel/SharedWorkflows/.github/workflows/auto-approve-owner-pr.yml@v1.0.0
    permissions:
      pull-requests: write
