# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: TheManOfTeel/SharedWorkflows/.github/workflows/node-ci.yml@v1.0.0
    with:
      working-directory: ./Source/ClientApp
      node-version: 24.x
      cache: npm
      cache-dependency-path: ./Source/ClientApp/package-lock.json
      install-command: npm ci
      build-command: npm run build --if-present
      test-command: npm test